# Text

A span of text, possibly modified with semantic meaning like emphasis or strong
importance.

Text supports the following modifiers that alter the text's semantic meaning and
typographic attributes:

emphasize::
  Indicates that the text should be emphasized or is in an alternate voice,
  often represented by an italic font style.
strong::
  Indicates that the text has strong importance, often represented by a bold
  text style.
position::
  Indicates that the text should typeset as subscript or superscript, often
  represented as smaller and higher or lower than the surrounding text.
strikethrough::
  Indicates that the text is no longer relevant or accurate or has been removed
  in an edit, often represented by a line through the middle of the text.
link::
  Indicates that the text references an external or internal web resource,
  usually represented as a clickable link that redirects the browser to the
  resource.

Multiple modifiers may be used together.

## Supported Consumers

- [x] Apple News
- [x] AMP
- [x] Facebook Instant Articles

All three consumers render Text as a text string within its parent
<<Paragraph>>. If there are any semantic modifiers on the Text, those are
rendered using the following tags:

emphasize::
  Uses a `<em>` tag.
strong::
  Uses a `<strong>` tag.
position::
  Uses a `<sub>` or `<sup>` tag for `"subscript"` and `"superscript"`,
  respectively
strikethrough::
  Uses a `<s>` tag.
link::
  Uses a `<a>` tag with the `href` attribute pointing to the URL.



## Parameters

.Parameters
|===
|Field |Type |Required |Description

|"text"
|string
|Required
|The text in this span.

|"emphasize"
|boolean
|Optional (default false)
|Whether this text should be emphasized.

|"strong"
|boolean
|Optional (default false)
|Whether this text should be marked with strong importance.

|"position"
|"subscript"\|"superscript"
|Optional
|The position of the text, either subscripted or superscripted.

|"strikethrough"
|boolean
|Optional (default false)
|Whether this text should be marked as stricken.

|"link"
|url
|Optional
|Url to which this text links.

|===

## Examples

[source,json]
----
{
  "@type": "paragraph",
  "content": [
    {
      "@type": "text",
      "text": "The red fox jumped over the white fence."
    }
  ]
}
----

[source,json]
----
{
  "@type": "paragraph",
  "content": [
    {
      "@type": "text",
      "text": "It is "
    },
    {
      "@type": "text",
      "emphasize": true,
      "text": "imperative"
    },
    {
      "@type": "text",
      "text": " that we act."
    }
  ]
}
----

[source,json]
----
{
  "@type": "paragraph",
  "content": [
    {
      "@type": "text",
      "text": "We must act "
    },
    {
      "@type": "text",
      "strong": true,
      "text": "now"
    },
    {
      "@type": "text",
      "text": "!"
    }
  ]
}
----

[source,json]
----
{
  "@type": "paragraph",
  "content": [
    {
      "@type": "text",
      "text": "The chemical formula of water is H"
    },
    {
      "@type": "text",
      "position": "subscript",
      "text": "2"
    },
    {
      "@type": "text",
      "text": "O."
    }
  ]
}
----
