[[ImageComponent]]
= Image

An image in a one of the following web formats:
- PNG
- JPEG
- GIF

== Supported Consumers

- [x] Apple News
- [x] AMP
- [x] Facebook Instant Articles

=== Apple News

Renders as a `Figure` component.

If `"alt"` is provided its text is added to the `accessibilityCaption`
property of the `Figure`.

If `"caption"` is provided its text is added to the `caption` property of the
`Figure`.

If `"attribution"` is provided and `"caption"` is not provided, the text of
`"attribution"` is added to the `caption` property of the `Figure`. If both
`"attribution"` and `"caption"` are provided then the text of `"attribution"` is
appended to the `"caption"` with a space and both text are added to the
`caption` property of the `Figure`.

=== AMP

If `"format"` is `"png"` or `"jpeg"` it renders as an `<amp-img>` tag; if
`"format"` is `"gif"` it renders as an `<amp-img>` nested in an `<amp-anim>`.

If `"attribution"` is provided, the `"attribution"` attribute on the `<amp-img>`
is populated with the `"attribution"` text.

If `"caption"` is provided the output is wrapped in a `<figure>` tag and a
`<figcaption>` tag is added to the bottom containing the `"caption"` content.

=== Facebook Instant Articles

If `"format"` is `"png"` or `"jpeg"` it renders as an `Image` component; if
`"format"` is `"gif"` it renders as an `"Animated GIF"` component.

== Parameters

.Parameters
|===
|Field |Type |Required |Description

|"url"
|Url
|Required
|Url to the image.

|"format"
|"png"\|"jpeg"\|"gif"
|Required
|Format of the image. Currently only PNG, JPEG and GIF are supported.

|"width"
|integer
|Required
|Width of the image in pixels. Recommended minimum of 2048. Must not exceed
6000.

|"height"
|integer
|Required
|Height of the image in pixels. Recommended minimum of 2048. Must not exceed
6000.

|"alt"
|string
|Required
|Short, descriptive title of the image for screen readers.

|"caption"
|Text
|Optional
|A longer caption that describes the image or provides context.

|"attribution"
|Text
|Optional
|An attribution of your image source, copyright statement, etc.

|===

== Examples

[source,json]
----
{
  "@type": "image",
  "format": "jpeg",
  "url": "[omitted]",
  "width": 600,
  "height": 371,
  "alt": "Stop Deportations Rally",
  "caption": "A group of protestors holding up a \"Stop Deportations\" sign.",
  "attribution": {
    "@type": "text",
    "text": "Source: Shutterstock"
  }
}
----
