[[ImageComponent]]
= Image

An image in a one of the following web formats:
- PNG
- JPEG
- GIF

== Supported Consumers

- [x] Apple News
- [x] AMP
- [x] Facebook Instant Articles

=== Apple News

Renders as a `Figure` component.

If `"alt"` is provided its text is added to the `accessibilityCaption`
property of the `Figure`.

If `"caption"` is provided its text is added to the `caption` property of the
`Figure`.

If `"attribution"` is provided and `"caption"` is not provided, the text of
`"attribution"` is added to the `caption` property of the `Figure`. If both
`"attribution"` and `"caption"` are provided then the text of `"attribution"` is
appended to the `"caption"` with a space and both text are added to the
`caption` property of the `Figure`.

=== AMP

If `"format"` is `"png"` or `"jpeg"` it renders as an `<amp-img>` tag; if
`"format"` is `"gif"` it renders as an `<amp-img>` nested in an `<amp-anim>`.

If `"attribution"` is provided, the `"attribution"` attribute on the `<amp-img>`
is populated with the `"attribution"` text.

If `"caption"` is provided the output is wrapped in a `<figure>` tag and a
`<figcaption>` tag is added to the bottom containing the `"caption"` content.

=== Facebook Instant Articles

If `"format"` is `"png"` or `"jpeg"` it renders as an `Image` component; if
`"format"` is `"gif"` it renders as an `"Animated GIF"` component.

== Parameters

.Parameters
|===
|Field |Type |Required |Description

|"imageResource"
|<<ImageResource>>
|Required
|Image resource to be rendered.

|"alt"
|<<string>>
|Required
|Short, descriptive title of the image for screen readers.

|"caption"
|<<Text>>
|Optional
|A longer caption that describes the image or provides context.

|"attribution"
|<<Text>>
|Optional
|An attribution of your image source, copyright statement, etc.

|===

== Invariants

- `imageResource[width]` and `imageResource[height]` should be at least 2048,
  and must be smaller than 6000.footnote:[Facebook Instant articles recommends
  2048x2048 min image dimensions and requires a max of 6000x6000.]
- Image pointed at by `imageResource[url]` must be less than 8MB.
  footnote:[Facebook Instant articles supports images up to 8MB in size.]

== Examples

[source,json]
----
{
  "@type": "image",
  "imageResource": {
    "url": "https://example.com/images/example.jpeg",
    "format": "jpeg",
    "width": 4048,
    "height": 2048
  },
  "alt": "Alt text",
  "caption": "A short description of the image.",
  "attribution": {
    "@type": "text",
    "text": "Source: John Doe"
  }
}
----
