[[Text]]
= Text

A group of semantically- or typographically-related text.

Plain text with no modifiers is represented as a JSON <<string>>, while text
containing one or more modifiers is represented as an array of
<<string,strings>> and nested JSON objects (see Parameters section below for the
shape of the JSON object). Text consisting of a single modifier applying to the
entire content is represented as a single JSON object (*not* as an array since
that would be redundant).

Formally, Text may be represented as the following type union in Typescript
notation:

[source,typescript]
----
type Text = string | TextWithModifiers | Array<string | TextWithModifiers>

interface TextWithModifiers {
  isEmphasized?: bool,
  isStrong?: bool,
  isStrikethrough?: bool,
  isUnderlined?: bool,
  isCode?: bool,
  textPosition?: 'baseline' | 'subscript' | 'superscript',
  link?: Url,
  text: Text
}
----

Text supports the following modifiers that alter the contained text's semantic
meaning and typographic attributes:

isEmphasized::
  Indicates that the text should be emphasized or is in an alternate voice,
  often represented by an italic font style.
isStrong::
  Indicates that the text has strong importance, often represented by a bold
  text style.
isStrikethrough::
  Indicates that the text is no longer relevant or accurate or has been removed
  in an edit, often represented by a line through the middle of the text.
isUnderlined::
  Indicates that the text should be underlined. Note that this does not indicate
  importance or emphasis, it is purely for stylistically offsetting the text
  from the surrounding text.
isCode::
  Indicates that the text contains a snippet of computer code, usually rendered
  in a monospace font.
textPosition::
  Indicates that the text should typeset as subscript or superscript, often
  represented as smaller and higher or lower than the surrounding text.
link::
  Indicates that the text refers to a web resource.

Multiple modifiers may be used together on the same text, and modifiers may be
nested by nesting text components.

== Supported Consumers

- [x] Apple News
- [x] AMP
- [x] Facebook Instant Articles

All three consumers render Text as a text string. If there are any semantic
modifiers on the Text, those are rendered using the following tags:

isEmphasized::
  Uses a `<em>` tag.
isStrong::
  Uses a `<strong>` tag.
isStrikethrough::
  Uses a `<s>` tag.
isUnderlined::
  Uses a `<u>` tag.
isCode::
  Uses a `<code>` tag.
textPosition::
  Uses a `<sub>` or `<sup>` tag for `"subscript"` and `"superscript"`,
  respectively
link::
  Uses a `<a>` tag with its href attribute set to the url.

== Parameters

.Parameters
|===
|Field |Type |Required |Description

|"text"
|<<Text>>
|Required
|The group of text. May contain nested Text or plain strings. Plain strings are
always escaped to prevent CWE-79 (Cross-site scripting) attacks.

|"isEmphasized"
|<<bool>>
|Optional (default false)
|Whether this text should be emphasized.

|"isStrong"
|<<bool>>
|Optional (default false)
|Whether this text should be marked with strong importance.

|"isStrikethrough"
|<<bool>>
|Optional (default false)
|Whether this text should be marked as stricken.

|"isUnderlined"
|<<bool>>
|Optional (default false)
|Whether this text should be marked as underlined.

|"isCode"
|<<bool>>
|Optional (default false)
|Whether this text should be marked as computer code.

|"textPosition"
|"baseline" \| "subscript" \| "superscript"
|Optional (default "baseline")
|The position of the text, either baseline, subscripted or superscripted.

|"link"
|<<Url>>
|Optional
|URL that identifies a web resource referred to by this text.

|===

== Examples

.Example 1: Plain text
`The red fox jumped over the white fence.`
[source,json]
----
"The red fox jumped over the white fence."
----

.Example 2: Common Modifiers
`It is _imperative_ that [line-through]#you# we [underline]#act# *now*!`
[source,json]
----
[
  "It is ",
  {
    "isEmphasized": true,
    "text": "imperative"
  },
  " that ",
  {
    "isStrikethrough": true,
    "text": "you"
  },
  " we ",
  {
    "isUnderlined": true,
    "text": "act"
  },
  " ",
  {
    "isStrong": true,
    "text": "now"
  },
  "!"
]
----

.Example 3: Links and Nested Modifiers
`According to _https://en.wikipedia.org/wiki/Water[Wikipedia]_, the chemical formula of water is *H~2~O*.`
[source,json]
----
[
  "According to ",
  {
    "isEmphasized": true,
    "link": "https://en.wikipedia.org/wiki/Water",
    "text": "Wikipedia"
  },
  ", the chemical formula of water is ",
  {
    "isStrong": true,
    "text": [
      "H",
      {
        "textPosition": "subscript",
        "text": "2"
      },
      "O"
    ]
  },
  "."
]
----
